{% set name = "autodocsumm" %}
{% set version = "0.2.7" %}
{% set sha256 = "cea7e2f900e5ac10baa6e831683e9241b0892226210609c087b94f109e0f6ab6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - sphinx >=2.2
    - six

test:
  imports:
    - autodocsumm

about:
  home: https://github.com/Chilipp/autodocsumm
  license: Apache-2.0
  license_file: LICENSE
  summary: Extending your autodoc API docs with a summary

  description: |
    This sphinx extension provides some useful extensions to the Sphinxs
    autodoc_ extension. Those include automatic and grouped summary tables for
    modules and classes, as well as documenting the __call__ method
  doc_url: http://autodocsumm.readthedocs.io/
  dev_url: https://github.com/Chilipp/autodocsumm

extra:
  recipe-maintainers:
    - Chilipp
