{% set name = "autodocsumm" %}
{% set version = "0.1.6" %}
{% set sha256 = "baeeb983ae5676005b72965299a7768c73c38b31804a4852e280f10ce7c65fee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - sphinx
    - six

test:
  imports:
    - autodocsumm

about:
  home: https://github.com/Chilipp/autodocsumm
  license: GPL-2.0
  license_family: GPL2
  license_file: LICENSE
  summary: 'Extending your autodoc API docs with a summary'

  description: |
    This sphinx extension provides some useful extensions to the Sphinxs
    autodoc_ extension. Those include automatic and grouped summary tables for
    modules and classes, as well as documenting the __call__ method
  doc_url: http://autodocsumm.readthedocs.io/
  dev_url: https://github.com/Chilipp/autodocsumm

extra:
  recipe-maintainers:
    - Chilipp
