travis:
  secure:
    BINSTAR_TOKEN: O/gzfa8koIHz900+0jSFExuS5laEvhtGS5lE5cb+VlOeFUazmJkfI2gKQg7DXnVtP8wmCFH9swbHrsIwc0glk7UAM9YbvhlzuvVqPlICB3P83lGpl0pmGi+N7IkM8W1GAr3Xk3iAtUJemcMem2dIsmtbExYnEZuZ+pNZg6ufwKDJCxEVD9XkYZH1mxDeT5iLoriZHbD8BpleBo6C12UmtQFru1U1Bu1zPATGN6gKwhQLkxxrJteb+McgrhWhHLW1BGSkRkaeBRZ2x2CJpwU2I04jDOXIiXNnTj35RYoudh4hweJDZHyIZ9a0TXtemFwRMxC04LBle4FaSu51GLxVwTMynbhGhchnOjDzouc8xlQX9xLIY8TL/JmX9WddqsSw1zMNVD2d3Y7GgV8Qs+m8m9/wRFqQ2Nof0EOwHyCVnzfhe1xm7gx+rNIkciCuZOu3qto88mEqfo+os1dxJp52WdBgVS3hW5j6+LqLIP6RaaybMg7tq14A8aoVx/RonhI8mz1M9bpD8Jw+3VIXX7mk4hwZMbjfLpaH3Q7q3Y0JmsGdblFUsr3jxWNM7tFJzViFhgFWehE2NBEWxuAK8HqeHFIvLlxz5FSkBoVNcTgVvzdfr5V8hQEcRHKCBYXuJ4K/3rkhNaGPHi2e7AvNanajO1WFzbyCqDf3qHAEti5PhtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
