travis:
  secure:
    BINSTAR_TOKEN: t7Pr4vMj7xa77aUn8tjHge2+1YhSZAVNt7nPekICE1erAru6u7qGRQ+fuNATUORW+ABNkj5oJlrXiPX/1Avf4ZsrPIcZgxjExmdN+PC2gdDfwGyn8q7kFn4oV0wZiWYm+TjGMS9JwnJ5Uq5PptMiHOaWD/tOm9oOHpztcYlZgBzThu1B2qXbQQXqY91B7ExNv6vfD2Vs42nvHf0aNZrUu9epgGGeeAaP0qpkRIQZxZSHNcJc1Cl5US5gp3BYA6tERUUVscEwQF0E6l49GnbYaRLVRY7bF3stAFWIP8zrOQDYrSoufEFLLX+t0HWKCszXux9OHdRJAeGlnIgRPYsE5Gm531BY+QHHPP9GIJ3nhYyhXqVuyMEMIqZUF6k5Pz/IB0352KIqr5bOWrtHVAIvDnbclJoHH+hri7XZehkV6kC/fqLapYjZR1efs1DmoRJ7An2NQLqUZE6I5fSE3MI9yvOnjyP9H2mgmwYtcI4pDJyB4K615VO8S+rWgMHZqYIsT2B2Nz5B+NryNi+q2ZfozS5kf+A6C98BCwp1j8afuJfN2FM9i8Iyy1sg75Aty9D++7Kvo2xsPGYNL0Z5Q2oI939bFHIDxMBLYEW6ot2wht1Kqui0k5+7QiIrCZwzN90wuVOKdQ8IyWvWcLQYBJOfhoBwZyT6wghpSkHt7e6UWl0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
